config/routes.rb
Rails.application.routes.draw do
  root 'friends#index'
  get 'search' => 'friends#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  searchkick
  Friend.reindex
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def search
    @friends = Friend.search(params[:search])
  end
  
  def index
    @friends = Friend.all
  end
end

# products = Product.search("apples")
# products.each do |product|
#   puts product.name
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<% @friends.each do |friend| %>
  <p><%= friend.name %></p>
<% end %>

app/views/friends/search.html.erb
Searching... for that something that I'll never find. In another place, another time!

<% if @friends.length == 0 %>
  <h4>No results matched your search - spell correctly or get <em>more</em> friends</h4>
<% end %>

<% @friends.each do |friend| %>
  <p><%= friend.name %></p>
<% end %>

<p><%= link_to 'Back', root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchkickTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= form_tag search_path, method: :get, role: "search" do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search" %>
      </p>
    <% end %>
  <body>

    

    <%= yield %>
  </body>
</html>